### ISSUE TITLE
Only top of icons are clickable

### ISSUE THREAD

**Issue by manfredjoa** [alantothe/react_port#1]
It looks like you have 2 divs that are on top of each other, both with absolute positioning. The second div on the bottom half starts slightly below the tops of the icons, which is why only the tops are clickable. Once that is fixed, you may no longer need pt-32 on the "Web Applications" h1 tag, which may or may not also interfere with the click-ability of the icons. Hope this helps!

**Comment by alantothe** [comment]
thanks for the help Manfred, ill update the code
